version: "3"
services:
  webserver:
    build: # when the context is provided, we build the image
      context: ./webserver
      dockerfile: Dockerfile
    container_name: "nginx"
    
    ports:
      - 8080:80
      - 443:443
  app: # this name is used in Nginx's "proxy_pass"  directive
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app